--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-20-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_ASISTENCIA
--------------------------------------------------------

  CREATE TABLE "TEST"."T_ASISTENCIA" 
   (	"ID" NUMBER, 
	"RUN_USUARIO" NUMBER(8,0), 
	"FECHA" DATE, 
	"ESTADO" NUMBER, 
	"HORA_INGRESO" DATE, 
	"HORA_SALIDA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_COMUNA
--------------------------------------------------------

  CREATE TABLE "TEST"."T_COMUNA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"ID_REGION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_EVALUACION_DESEMPENO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_EVALUACION_DESEMPENO" 
   (	"ID" NUMBER, 
	"RUN_EVALUADO" NUMBER(8,0), 
	"FECHA_INICIO" DATE, 
	"FECHA_TERMINO" DATE, 
	"NOTA" NUMBER, 
	"DETALLE" VARCHAR2(500 BYTE), 
	"RUN_EVALUADOR" NUMBER(8,0), 
	"FECHA_EVALUACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_FUNCIONARIO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_FUNCIONARIO" 
   (	"RUN" NUMBER(8,0), 
	"RUNDV" VARCHAR2(1 BYTE), 
	"NOMBRES" VARCHAR2(250 BYTE), 
	"PATERNO" VARCHAR2(250 BYTE), 
	"MATERNO" VARCHAR2(250 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"PASSWORD" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"FONO_PERSONAL_FIJO" VARCHAR2(50 BYTE), 
	"FONO_PERSONAL_MOVIL" VARCHAR2(50 BYTE), 
	"FONO_LABORAL_FIJO" VARCHAR2(50 BYTE), 
	"FONO_LABORAL_MOVIL" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(250 BYTE), 
	"NUMERO" VARCHAR2(10 BYTE), 
	"ID_REGION" NUMBER, 
	"ID_COMUNA" NUMBER, 
	"FECHA_INICIO_TRABAJO_EMPRESA" DATE, 
	"ID_TIPO_FUNCIONARIO" NUMBER, 
	"ID_UNIDAD" NUMBER, 
	"ID_CARGO" NUMBER, 
	"FECHA_CREACION" DATE, 
	"RUN_CREADOR" NUMBER, 
	"FOTOGRAFIA" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_FUNCIONARIO_CARGO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_FUNCIONARIO_CARGO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"FECHA_CREACION" DATE, 
	"RUN_CREADOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_FUNCIONARIO_TIPO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_FUNCIONARIO_TIPO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(300 BYTE), 
	"FECHA_CREACION" DATE, 
	"RUN_CREADOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ORGANIZACION
--------------------------------------------------------

  CREATE TABLE "TEST"."T_ORGANIZACION" 
   (	"RUT" NUMBER(8,0), 
	"RAZONSOCIAL" VARCHAR2(250 BYTE), 
	"TIPO" VARCHAR2(250 BYTE), 
	"FINALIDAD" VARCHAR2(500 BYTE), 
	"DIRECCION" VARCHAR2(500 BYTE), 
	"NUMERO" NUMBER(10,0), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"WEB" VARCHAR2(250 BYTE), 
	"LOGOTIPO" VARCHAR2(500 BYTE), 
	"ID_REGION" NUMBER, 
	"ID_COMUNA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PERMISO_ESTADO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_PERMISO_ESTADO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PERMISO_FUNCIONARIO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_PERMISO_FUNCIONARIO" 
   (	"ID" NUMBER, 
	"RUN_FUNCIONARIO" NUMBER(8,0), 
	"ID_PERMISO_TIPO" NUMBER, 
	"RUN_SOLICITA" NUMBER(8,0), 
	"FECHA_INICIO" DATE, 
	"FECHA_TERMINO" DATE, 
	"DIAS" NUMBER, 
	"FECHA_CREACION" DATE, 
	"FECHA_AUTORIZACION" DATE, 
	"RUN_CREADOR" NUMBER(8,0), 
	"RUN_AUTORIZADOR" NUMBER(8,0), 
	"ID_PERMISO_ESTADO" NUMBER, 
	"ID_RESOLUCION" NUMBER, 
	"CODIGO_VERIFICACION" VARCHAR2(250 BYTE), 
	"ID_MOTIVO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PERMISO_LEGAL
--------------------------------------------------------

  CREATE TABLE "TEST"."T_PERMISO_LEGAL" 
   (	"ID_PERMISO_TIPO" NUMBER, 
	"ANOS" NUMBER, 
	"DIAS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PERMISO_MOTIVO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_PERMISO_MOTIVO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PERMISO_TIPO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_PERMISO_TIPO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"FECHA_CREACION" DATE, 
	"RUN_CREADOR" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_REGION
--------------------------------------------------------

  CREATE TABLE "TEST"."T_REGION" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_RESOLUCION
--------------------------------------------------------

  CREATE TABLE "TEST"."T_RESOLUCION" 
   (	"ID" NUMBER, 
	"ID_UNIDAD" NUMBER, 
	"MES" NUMBER, 
	"ANO" NUMBER, 
	"RUN_GENERADOR" NUMBER(8,0), 
	"CORRELATIVO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_SECCION
--------------------------------------------------------

  CREATE TABLE "TEST"."T_SECCION" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"RUTA" VARCHAR2(250 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_SECCION_CARGO
--------------------------------------------------------

  CREATE TABLE "TEST"."T_SECCION_CARGO" 
   (	"ID_CARGO" NUMBER, 
	"ID_SECCION" NUMBER, 
	"FECHA_CREACION" DATE, 
	"RUN_CREADOR" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_UNIDAD
--------------------------------------------------------

  CREATE TABLE "TEST"."T_UNIDAD" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(250 BYTE), 
	"RUN_JEFE" VARCHAR2(8 BYTE), 
	"FECHA_CREACION" DATE, 
	"RUN_CREADOR" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TEST.T_ASISTENCIA
SET DEFINE OFF;
REM INSERTING into TEST.T_COMUNA
SET DEFINE OFF;
REM INSERTING into TEST.T_EVALUACION_DESEMPENO
SET DEFINE OFF;
REM INSERTING into TEST.T_FUNCIONARIO
SET DEFINE OFF;
REM INSERTING into TEST.T_FUNCIONARIO_CARGO
SET DEFINE OFF;
REM INSERTING into TEST.T_FUNCIONARIO_TIPO
SET DEFINE OFF;
REM INSERTING into TEST.T_ORGANIZACION
SET DEFINE OFF;
REM INSERTING into TEST.T_PERMISO_ESTADO
SET DEFINE OFF;
REM INSERTING into TEST.T_PERMISO_FUNCIONARIO
SET DEFINE OFF;
REM INSERTING into TEST.T_PERMISO_LEGAL
SET DEFINE OFF;
REM INSERTING into TEST.T_PERMISO_MOTIVO
SET DEFINE OFF;
REM INSERTING into TEST.T_PERMISO_TIPO
SET DEFINE OFF;
REM INSERTING into TEST.T_REGION
SET DEFINE OFF;
REM INSERTING into TEST.T_RESOLUCION
SET DEFINE OFF;
REM INSERTING into TEST.T_SECCION
SET DEFINE OFF;
REM INSERTING into TEST.T_SECCION_CARGO
SET DEFINE OFF;
REM INSERTING into TEST.T_UNIDAD
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table T_ASISTENCIA
--------------------------------------------------------

  ALTER TABLE "TEST"."T_ASISTENCIA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_COMUNA
--------------------------------------------------------

  ALTER TABLE "TEST"."T_COMUNA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_EVALUACION_DESEMPENO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_EVALUACION_DESEMPENO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_FUNCIONARIO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_FUNCIONARIO" MODIFY ("RUN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_FUNCIONARIO_CARGO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_FUNCIONARIO_CARGO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_FUNCIONARIO_TIPO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_FUNCIONARIO_TIPO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "TEST"."T_ORGANIZACION" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PERMISO_ESTADO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_PERMISO_ESTADO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PERMISO_FUNCIONARIO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_PERMISO_FUNCIONARIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PERMISO_LEGAL
--------------------------------------------------------

  ALTER TABLE "TEST"."T_PERMISO_LEGAL" MODIFY ("ANOS" NOT NULL ENABLE);
  ALTER TABLE "TEST"."T_PERMISO_LEGAL" MODIFY ("ID_PERMISO_TIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PERMISO_MOTIVO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_PERMISO_MOTIVO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PERMISO_TIPO
--------------------------------------------------------

  ALTER TABLE "TEST"."T_PERMISO_TIPO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_REGION
--------------------------------------------------------

  ALTER TABLE "TEST"."T_REGION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_SECCION
--------------------------------------------------------

  ALTER TABLE "TEST"."T_SECCION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_UNIDAD
--------------------------------------------------------

  ALTER TABLE "TEST"."T_UNIDAD" MODIFY ("ID" NOT NULL ENABLE);
